#!/bin/bash
for file_masks in "$@"
do
    if [ -f "$file_masks" ]
    then
        read -e -p "Enter new file name:" -i "$file_masks" new_name
        mv "$file_masks" "$new_name"
    fi
done

exit 0
